apiVersion: gateway.networking.k8s.io/v1
kind: BackendTLSPolicy
metadata:
  name: openbao-ui-envoy
  namespace: vault-system
spec:
  targetRefs:
    - group: ""
      kind: Service
      name: openbao-active
  validation:
    hostname: openbao-active.vault-system
    caCertificateRefs:
      - group: ""
        kind: ConfigMap
        name: openbao-ca
