apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: simple-flask-gw
spec:
  gatewayClassName: traefik
  listeners:
    - name: websecure
      protocol: HTTPS
      port: 8443
      hostname: "simple-flask.lab.local"
      tls:
        mode: Terminate
        certificateRefs:
          - name: simple-flask-tls
      allowedRoutes:
        namespaces:
          from: Selector
          selector:
            matchLabels:
              gateway: simple-flask
        kinds:
          - kind: HTTPRoute 
    - name: web
      protocol: HTTP
      port: 8000
      hostname: "simple-flask.lab.local"
      allowedRoutes:
        namespaces:
          from: Selector
          selector:
            matchLabels:
              gateway: simple-flask
        kinds:
          - kind: HTTPRoute 
