kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: bao
nodes:
- role: control-plane
  image: kindest/node:v1.34.8
- role: worker
  image: kindest/node:v1.34.8
- role: worker
  image: kindest/node:v1.34.8
- role: worker
  image: kindest/node:v1.34.8
networking:
  podSubnet: "10.16.0.0/16"
  serviceSubnet: "10.128.0.0/12"
  disableDefaultCNI: false
