apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: bao-secrets-sync
spec:
  refreshInterval: "120s"
  secretStoreRef:
    name: openbao
    kind: SecretStore
  target:
    name: test-bao-secrets-sync
  data:
    - secretKey: secret-vaules.yaml
