apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: openbao
spec:
  provider:
    vault:
      auth:
        kubernetes:
          mountPath: kubernetes
          role: external-secrets-read
          serviceAccountRef:
            audiences:
            - vault
            name: external-secrets-bao-read
            namespace: vault-system
        namespace: lab
      caProvider:
        key: ca.crt
        name: openbao-tls
        namespace: vault-system
        type: Secret
      namespace: lab
      path: flux-gitops-values
      server: https://openbao.vault-system:8200
      version: v2
