apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: bao-secrets-sync
spec:
  refreshInterval: "120s"
  refreshPolicy: OnChange
  secretStoreRef:
    name: openbao
    kind: ClusterSecretStore
  target:
    name: test-bao-secrets-sync
    template:
      metadata:
        labels:
          reconcile.fluxcd.io/watch: "true"
  data:
    - secretKey: secret-values.yaml
      remoteRef:
        key: lab/springpetclinic
        property: secret-values.yaml
