apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: openbao
spec:
  provider:
    vault:
      server: "https://openbao.vault-system:8200"
      namespace: "lab"
      path: "secret/flux-gitops-values"
      version: "v2"
      auth:
        # Authenticate against Vault using a Kubernetes ServiceAccount
        # token stored in a Secret.
        # https://www.vaultproject.io/docs/auth/kubernetes
        kubernetes:
          # Path where the Kubernetes authentication backend is mounted in Vault
          mountPath: "kubernetes"
          # A required field containing the Vault Role to assume.
          role: "external-secrets-read"
          # Optional service account field containing the name
          # of a kubernetes ServiceAccount
          serviceAccountRef:
            name: "external-secrets-bao-read"
            namespace: "vault-system"
            audiences:
              - "vault"
      caProvider:
        type: "Secret"
        name: "openbao-tls"
        namespace: "vault-system"
        key: "ca.crt"
