apiVersion: v1
kind: Service
metadata:
  name: {{ include "simple-flask.fullname" . }}
  labels:
    {{- include "simple-flask.labels" . | nindent 4 }}
  {{- if and .Values.traefik.ingress.enabled .Values.traefik.ingress.stickySession.enabled }}
  annotations:
    traefik.ingress.kubernetes.io/service.sticky.cookie: "true"
    traefik.ingress.kubernetes.io/service.sticky.cookie.name: TRAEFIK_SESSION
    traefik.ingress.kubernetes.io/service.sticky.cookie.secure: "true"
    traefik.ingress.kubernetes.io/service.sticky.cookie.httponly: "true"
  {{- end }}
spec:
  selector:
    {{- include "simple-flask.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.app.port }}
  type: {{ .Values.service.type }}
---
{{- if .Values.loadBalancer.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "simple-flask.fullname" . }}-lb
  labels:
    {{- include "simple-flask.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "simple-flask.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.app.port }}
  type: LoadBalancer
{{- end }}
